# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20161104_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day1',
            new_name='presentDay1',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day10',
            new_name='presentDay10',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day11',
            new_name='presentDay11',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day12',
            new_name='presentDay12',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day13',
            new_name='presentDay13',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day14',
            new_name='presentDay14',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day15',
            new_name='presentDay15',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day16',
            new_name='presentDay16',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day17',
            new_name='presentDay17',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day18',
            new_name='presentDay18',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day19',
            new_name='presentDay19',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day2',
            new_name='presentDay2',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day20',
            new_name='presentDay20',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day21',
            new_name='presentDay21',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day22',
            new_name='presentDay22',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day23',
            new_name='presentDay23',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day24',
            new_name='presentDay24',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day25',
            new_name='presentDay25',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day26',
            new_name='presentDay26',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day27',
            new_name='presentDay27',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day28',
            new_name='presentDay28',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day29',
            new_name='presentDay29',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day3',
            new_name='presentDay3',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day30',
            new_name='presentDay30',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day31',
            new_name='presentDay31',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day4',
            new_name='presentDay4',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day5',
            new_name='presentDay5',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day6',
            new_name='presentDay6',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day7',
            new_name='presentDay7',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day8',
            new_name='presentDay8',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day9',
            new_name='presentDay9',
        ),
    ]
