# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20161105_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay1',
            new_name='present_day1',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay10',
            new_name='present_day10',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay11',
            new_name='present_day11',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay12',
            new_name='present_day12',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay13',
            new_name='present_day13',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay14',
            new_name='present_day14',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay15',
            new_name='present_day15',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay16',
            new_name='present_day16',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay17',
            new_name='present_day17',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay18',
            new_name='present_day18',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay19',
            new_name='present_day19',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay2',
            new_name='present_day2',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay20',
            new_name='present_day20',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay21',
            new_name='present_day21',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay22',
            new_name='present_day22',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay23',
            new_name='present_day23',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay24',
            new_name='present_day24',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay25',
            new_name='present_day25',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay26',
            new_name='present_day26',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay27',
            new_name='present_day27',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay28',
            new_name='present_day28',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay29',
            new_name='present_day29',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay3',
            new_name='present_day3',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay30',
            new_name='present_day30',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay31',
            new_name='present_day31',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay4',
            new_name='present_day4',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay5',
            new_name='present_day5',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay6',
            new_name='present_day6',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay7',
            new_name='present_day7',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay8',
            new_name='present_day8',
        ),
        migrations.RenameField(
            model_name='monthjournal',
            old_name='presentDay9',
            new_name='present_day9',
        ),
    ]
